// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKPi_pGJy1nQUxULrAILp2paP5mO0KORg',
    appId: '1:997717290609:web:2c7e863c423bf8695475d0',
    messagingSenderId: '997717290609',
    projectId: 'puertask-c82b4',
    authDomain: 'puertask-c82b4.firebaseapp.com',
    storageBucket: 'puertask-c82b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFDQJyjgbi5eLsdWn_hDl-YMYrJlQqKDs',
    appId: '1:997717290609:android:de8ad656a60472415475d0',
    messagingSenderId: '997717290609',
    projectId: 'puertask-c82b4',
    storageBucket: 'puertask-c82b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkFct-5blGz8FU5Ys4f4DZKnz6lQVGqw',
    appId: '1:997717290609:ios:8be639719066724e5475d0',
    messagingSenderId: '997717290609',
    projectId: 'puertask-c82b4',
    storageBucket: 'puertask-c82b4.appspot.com',
    iosClientId: '997717290609-aebv3cl7rpg8f897qpeqf73e6an4qrrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.puresofttask1',
  );
}
